### ISSUE TITLE
Can't get Avg Ref Line or Trend Line to show up

### ISSUE THREAD

**Issue by mhoulio** [spotfiresoftware/spotfire-mod-violin#13]
For some reason I can't get the trend or ref line to show up for the Avg attribute.  Shows up in the ref table but not in the violin plot.  I highlighted a spot where the difference between the median and the Avg would be noticeable.  All other attributes plot perfectly.
![volin plot](https://github.com/spotfiresoftware/spotfire-mod-violin/assets/75500845/87354612-7129-4a28-8a2e-89a1d657a0ac)

**Comment by aberridg** [comment]
I've just published a new version of the Mod, v.2.6.0 - can you try that one please?

![image](https://github.com/spotfiresoftware/spotfire-mod-violin/assets/30839885/15ca8c04-793a-45e0-81f2-e84fbeeeff65)

![image](https://github.com/spotfiresoftware/spotfire-mod-violin/assets/30839885/8e172e96-54e7-419d-afdf-e6f6caa6da0e)

There were a few bugs in earlier versions.

**Comment by aberridg** [comment]
Closing, as believed to be fixed in v2.6.0 and v3.0.0
